spring:
  application:
    name: "jdbc_template_with_h2db"
  datasource:
    driver-class-name: org.h2.Driver
    #    initialize: true
    password: ''
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  sql:
    init:
      #      data-locations: classpath:data.sql
      encoding: UTF-8
#      schema-locations: classpath:data.sql