GET  http://localhost:8080  HTTP/1.1

### 1
POST http://localhost:8080/themeEntities HTTP/1.1
content-type: application/json

{
    "title": "sampleX",
    "body": "Wed, 21 Oct 2015 18:27:50 GMT"
}


### 2
GET http://localhost:8080/themeEntities HTTP/1.1


### 3
GET http://localhost:8080/themeEntities/98fde302-b4b0-4ab4-9946-f19229718b4e HTTP/1.1

### 4
DELETE http://localhost:8080/themeEntities/98fde302-b4b0-4ab4-9946-f19229718b4e HTTP/1.1

### 5
PATCH http://localhost:8080/themeEntities/85bed45f-8396-460a-a36f-a666f7a22b48 HTTP/1.1
content-type: application/json

{
    "title": "xxxx",
    "body": "yyyyy"
}